name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t alex452/alex452:latest
      - name: publish
        run: |
          docker login -u alex452 -p ${{ secrets.DOCKERHUB_TOKEN}}
          docker push alex452/alex452:latest
